name: steps examples

on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: configuração do node (pesquisar no marketplace...)
        uses: ???

      - name: verification of node version
        run: node --version
